alias pgstop='sudo systemctl stop postgresql@12-main.service'
alias deno='~/.deno/bin/deno'
alias cat='bat'
alias ub='cd ~/repos/utility-belt'
alias dt='cd ~/repos/data-tools'
alias pa='cd ~/repos/phoenix-api'
alias f='fuck'
alias p='pnpm'
alias pg='psql -d postgres -U stephen'
alias gtack='gstack'
alias oneq='sort -R ~/Documents/1-on-1-questions.txt | head -n 1' 
alias mdkir='mkdir'
alias ':q'='exit'
alias ls='lsd -1 --group-dirs first'
alias z='lazydocker'
alias v='/usr/local/bin/nvim.appimage'
alias nv='/usr/local/bin/neovide'
alias vconf='v ~/.config/nvim/lua/user/init.lua'
alias vp='openvpn3 session-start --config groundspeed-new'
alias vpd='openvpn3 session-manage --config groundspeed-new --disconnect'
alias vpl='openvpn3 sessions-list'
alias mg='mongo -uroot -p example --authenticationDatabase=admin localhost:20000/filetracker'
alias de='docker exec -it '
alias dtf='gstack project data-tools fixtures'
alias gbfs='gstack bundle filetracker start'
alias gss='gstack service '
alias gsp='gstack project '
alias gsb='gstack bundle '
alias gsi='gstack inspect '
alias gsc='gstack config '
alias gst='gstack status'
alias gsu='gstack update'
alias gpr='git push && gh pr create'
alias sortbylen='find ./ -type f -exec wc -l {} + | sort -rn'
alias sbl=sortbylen
alias gbs='git branch-select' 

# TSIQ
alias iq='cd ~/Dev/tsiq'
alias ai='cd ~/Dev/tsiq/application-intake-ui'
alias wb='cd ~/Dev/tsiq/iqos-workbench-api'
alias iql='export AWS_PROFILE=PackageReader && aws sso login'
alias iqt='export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain main --domain-owner 750763103106 --query authorizationToken --output text --region us-east-1)'

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

alias tag='aws ecr list-images --repository-name data-tools-app-prod | jq ".imageIds[0]"'

alias tsk='~/Dev/taskwarrior-tui/target/release/taskwarrior-tui'

gstop() {
  docker stop $(docker ps -a -q);
}
# gspb() {
#   gstack project "$1" build
# }

# gsps() {
#   gstack project "$1" start
# }

# gsbs() {
#   gstack bundle "$1" start
# }

alias python='python3'

alias grbd='gco dev && gp && gco - && git rebase dev'
alias gcof='git cof'
alias gec='git ec'
alias gecl='git ecl'
alias gl='git l'
alias glo='git lo'
alias gls='git ls'
alias glf='git lf'
alias gld='git ld'
alias glp='git lp'
alias gla='git la'
alias glao='git lao'
alias glas='git las'
alias glaf='git laf'
alias glad='git lad'
alias glap='git lap'
alias glg='git lg'
alias glgo='git lgo'
alias glgs='git lgs'
alias glgf='git lgf'
alias glgd='git lgd'
alias glgp='git lgp'
alias grl='git rl'
alias grlo='git rlo'
alias grlf='git rlf'
alias grld='git rld'
alias gsl='git sl'
alias gslo='git slo'
alias gslf='git slf'
alias gsld='git sld'
alias gsls='git sls'
alias gsh='git sh'
alias ggrep='git grep'
alias gd='git d'
alias gds='git ds'
alias gdc='git dc'
alias gdl='git dl'
alias gdu='git du'
alias gdr='git dr'
alias gs='git s'
alias gsi='git si'
alias gsa='git sa'
alias ga='git a'
alias gaa='git aa'
alias gau='git au'
alias gai='git ai'
alias gap='git ap'
alias gan='git an'
alias gu='git u'
alias gup='git up'
alias gc='git c'
alias gcn='git cn'
# alias gcc='git cc'
alias gcf='git cf'
alias gcs='git cs'
alias gca='git ca'
alias gcan='git can'
alias gco='git co'
alias gcom='git com'
alias gcod='git cod'
alias gcob='git cob'
alias gb='git b'
alias gbc='git bc'
alias gbd='git bd'
alias gbl='git bl'
alias gbla='git bla'
alias gt='git t'
alias gtc='git tc'
alias gtd='git td'
alias gcl='git cl'
alias gp='git p'
alias gf='git f'
alias gff='git ff'
alias gfa='git fa'
alias gfp='git fp'
alias gffp='git ffp'
alias gfap='git fap'
alias gpfa='git pfa'
alias gpu='git pu'
alias gpun='git pun'
alias gpuf='git puf'
alias gpuff='git puff'
alias gsub='git sub'
alias gsubu='git subu'
alias gm='git m'
alias gma='git ma'
alias gmc='git mc'
alias gmff='git mff'
alias gmnc='git mnc'
alias gr='git r'
alias gra='git ra'
alias grc='git rc'
alias grq='git rq'
alias grs='git rs'
alias gret='git ret'
alias grsh='git rsh'
alias gri='git ri'
alias griu='git riu'
alias grim='git rim'
alias grid='git rid'
alias gcp='git cp'
alias gcpa='git cpa'
alias gcpc='git cpc'
alias gcpq='git cpq'
alias grv='git rv'
alias grva='git rva'
alias grvc='git rvc'
alias grvq='git rvq'
alias gre='git re'
alias gres='git res'
alias greh='git reh'
alias gmt='git mt'
alias gdt='git dt'
alias gwhich='git which'
alias gwhichtg='git which-tag'
alias gwho='git who'
alias gwhoami='git whoami'
alias gwatch='git watch'
alias gthis='git this'
alias gthanks='git thanks'
alias gopen='git open'
alias gfork='git fork'
alias gfetchp='git fetch-pr'
alias gfetchm='git fetch-mr'
alias gsetupftch='git setup-fetch'
alias gwipe='git wipe'
alias gnuke='git nuke'
alias gctags='git ctags'
alias ggitignore='git gitignore'
alias gfbr='git fbr'
alias gfco='git fco'
alias gfcoc='git fcoc'
alias gfsha='git fsha'
alias gfshow='git fshow'
alias gfstash='git fstash'

